### PR TITLE
Replace VV integrator with Langevin splitting integrator

### PR DESCRIPTION
**Pull request by sgill2**
Replaces old perses VV integrator with a Langevin splitting integrator, which should help increase acceptance.

### CODE REVIEW

**Comment by davidlmobley** [comment]
@sgill2 - you've got a test failure, an undefined variable `nc_timestep`....

**Comment by sgill2** [comment]
@davidlmobley Tests are now passing, so this should be good for review now.

**Comment by sgill2** [comment]
@davidlmobley I'm using this integrator instead of the `AlchemicalLangevinIntegrator` for two reasons.

1. The main reason is that this integrator takes into account the work done during the MC moves. For whole-body rotations this wasn't really important, since we were performing them when `lambda=0` so there wasn't any change in the potential energy. But this comes up again when we start to consider other types of moves–like the sidechain rotations. The `AlchemicalLangevinIntegrator` doesn't do this, while `AlchemicalExternalLangevinIntegrator` does.

2. This inherited class adds some methods that were present in the old integrator, which provided a lot of convenience (ex. resetting the integraotr, getting the acceptance probability). Adding these methods makes it easy to swap in the new integrator into the existing `BLUES` code.

**Comment by sgill2** [comment]
@davidlmobley I'd edited the `AlchemicalExternalLangevinIntegrator` docstring to make it clear what the point of the integrator is and what it does differently than `AlchemicalLangevinIntegrator`. Also, I've updated the README.md talking about the integrator. Hopefully that addresses your requests above.

**Comment by sgill2** [comment]
After the merge with the latest master (from #87) the conda build fails. The error output is:
```
$ conda build --python $python devtools/conda-recipe
WARNING:stderrlog:
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/omnia
It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.
If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
Attempting to finalize metadata for blues
INFO:conda_build.metadata:Attempting to finalize metadata for blues
Leaving build/test directories:
  Work:	 ../../../miniconda/conda-bld/work 
  Test:	 ../../../miniconda/conda-bld/test_tmp 
Leaving build/test environments:
  Test:	source activate  ../../../miniconda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl 
  Build:	source activate  ../../../miniconda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place 
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1633, in build_tree
    notest=notest,
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 870, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 481, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 1635, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 623, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 269, in finalize_metadata
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 112, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/environ.py", line 682, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: ['mdtraj', 'openmm', 'openmmtools']
The command "conda build --python $python devtools/conda-recipe" failed and exited with 1 during .
Your build has been stopped.
```
This seems to be a problem with the omnia channel maybe? Considering it was working before I don't think it's a problem with the `install.sh` file. Any thoughts @davidlmobley ?

**Comment by davidlmobley** [comment]
@sgill2 - I do not have any insights on the conda error above. I would look at the Chodera lab repos using these and see if anything there has changed, as they would have the same issue. Possibly they have dropped py27 support (many packages will this  year!) or one of the packages has migrated away from omnia to conda-forge, or...? Take a quick look as they should be running tests on many packages that are using these same packages as dependencies, so you should be able to see how this is handled there.

Is py3x passing?

**Comment by davidlmobley** [comment]
@sgill2 - this is good to merge once tests pass, or if you want to merge it and deal with the tests in a separate PR we can also do so.

Once it's merged, bug me as we should do a new release.

**Pull request merged**
