### PR TITLE
Add external work alchemical Langevin splitting integrator

### PR DESCRIPTION
**Pull request by sgill2**
This PR aims to create an integrator that inherits from the openmmtools NonequilibriumLangevinIntegrator so that it also allows the non-alchemical protocol work to be measured.
- [x] get integrator working
- [x] write test to make sure it's handling the external work correctly

### CODE REVIEW

**Comment by davidlmobley** [comment]
Tagging @pgrinaway

**Comment by sgill2** [comment]
For a test I'll probably do something like the following: 
1.take an atom from an alanine dipeptide and distort it in a fixed way at some point in the middle of the nsteps_neq, while keeping lambdas constant. 
2.Assert that the protocol work != 0

**Comment by davidlmobley** [comment]
@sgill2 - you changed the title, is this ready for review?

**Comment by davidlmobley** [comment]
Also (not having looked at the code changes yet), as per the description of your PR, this adds an integrator, but does it switch the main code to use this integrator, or is the integrator "vestigial" (not used)? It would be good to document more completely here in this PR (and, if it's functional, in the relevant documentation). If it's just "vestigial" you'll want to create a separate issue(s) explaining what is going to be done with this from here.

**Comment by sgill2** [comment]
>Also (not having looked at the code changes yet), as per the description of your PR, this adds an integrator, but does it switch the main code to use this integrator, or is the integrator "vestigial" (not used)? It would be good to document more completely here in this PR (and, if it's functional, in the relevant documentation). If it's just "vestigial" you'll want to create a separate issue(s) explaining what is going to be done with this from here.

I suppose that's worth discussing now. 
Going from what John says about the splitting integrators (http://rspa.royalsocietypublishing.org/content/472/2189/20160138), it seems like having the BAOAB integration scheme as the default would be the best way to go for now. I'd say replace the VV integrator default with this integrator in the PR.

**Comment by sgill2** [comment]
But yeah, this should be about ready to review @davidlmobley. If @pgrinaway has a moment I'd also especially appreciate his input too.

**Comment by davidlmobley** [comment]
@sgill2 :
> I suppose that's worth discussing now. Going from what John says about the splitting integrators (http://rspa.royalsocietypublishing.org/content/472/2189/20160138), it seems like having the BAOAB integration scheme as the default would be the best way to go for now. I'd say replace the VV integrator default with this integrator in the PR.

Have you or Nathan done any tests on this yet to see what it does to acceptance, etc.?

(Though I think this also relates to the other issue we're currently discussing, in that if you go to an integrator in `openmmtools` you reduce code duplication.)

**Comment by davidlmobley** [comment]
Per discussion, this is going to be vestigial for now (see #50 and MMC) so the doc strings will need updating to indicate that.

**Comment by pgrinaway** [comment]
It looks good to me!

**Comment by davidlmobley** [comment]
OK, looks/sounds good, guys. Though we either need to update the doc strings to indicate this is vestigial (ideally with a link to this discussion) before merging this PR, or we need to create a separate issue to do so.

**Comment by nathanmlim** [comment]
I'm of the side we do it as a separate PR.

**Comment by davidlmobley** [comment]
OK, sounds fine.

**Pull request merged**
